-- MODIFYING THE USERS TABLE 
ALTER TABLE users MODIFY userid INT NOT NULL;
ALTER TABLE users MODIFY name VARCHAR(50) NOT NULL;
ALTER TABLE users MODIFY username VARCHAR(20) NOT NULL;
ALTER TABLE users MODIFY password VARCHAR(20) NOT NULL;

-- MODIFYING THE LOCATIONS TABLE
ALTER TABLE location MODIFY type INT NOT NULL;
ALTER TABLE location MODIFY description VARCHAR(50) NOT NULL;
ALTER TABLE location MODIFY lng REAL NOT NULL;
ALTER TABLE location MODIFY lat REAL NOT NULL;

-- MODIFYING THE PHOTOGRAPH TABLE
ALTER TABLE photographs MODIFY photoid INT NOT NULL;
ALTER TABLE photographs MODIFY locationid INT NOT NULL;


